### ISSUE TITLE
Any advice on how I would update these bindings to libadwaita latest stable?

### ISSUE THREAD

**Issue by ismyhc** [diamondburned/gotk4-adwaita#5]
Any advice on how I would update these bindings to libadwaita latest stable?

I'm on Fedora 38. And my devel package is:
```
Package libadwaita-devel-1.3.3-1.fc38.x86_64
```

**Comment by ismyhc** [comment]
Actually, I see there's a 1.2 branch. That may be sufficient for now. I was actually looking at the 1.4alpha libadwaita docs earlier by accident and noticed some changes there. AdwLeaflet -> AdwSplitNavigationView.

Anyways, Im still a bit curious about the process of generating newer bindings, but not  urgent. :)

**Comment by diamondburned** [comment]
The process is quite awkward if you're not already familiar with Nix, but it involves bumping the Nixpkgs commit in `shell.nix` and running `go generate` again. Generally, I don't try to bump stuff unless there's something that I really need.

f4ff0c6 is on libadwaita 1.4 now, so that might be worth a look.
