### ISSUE TITLE
Problematic build times

### ISSUE THREAD

**Issue by abergmeier** [diamondburned/gotk4-adwaita#6]
When using this library, it seems to spawn gcc and builds for 30m+.
Why is that and can this offloaded/cached?

**Comment by diamondburned** [comment]
> Why is that

See https://github.com/diamondburned/gotk4/issues/53#issuecomment-1001109930 and https://github.com/golang/go/issues/9887#issuecomment-913056050.

> can this offloaded/cached

It's already cached by the Go compiler, but only once the whole package has finished building. The longest offender is `gtk/v4`, so as soon as that's done, then you should be good.

Closing this since it's not something that I can directly address in gotk4-adwaita. It's either fixed in gotk4 or, most ideally, in the Go compiler (cmd/cgo) itself.
